### PR TITLE
Allow {{#or}} to accept variable arguments

### PR DESCRIPTION
**Pull request by spacedawwwg**
Unable to generate new docs though.

https://github.com/assemble/handlebars-helpers/issues/203

### CODE REVIEW

**Comment by spacedawwwg** [comment]
I'm just wondering what the review process is for pull requests? I'm using my personal fork in my projects at the moment but it would be nice to use the NPM version

**Comment by jonschlinkert** [comment]
@spacedawwwg I just [invited you](https://github.com/assemble/handlebars-helpers/invitations) to be a collab.

**Comment by jonschlinkert** [comment]
you also have publish rights on npm now

**Comment by jonschlinkert** [comment]
> Unable to generate new docs though.

don't worry about docs. I can take care of that until we release the next version of verb. thx though

**Comment by jonschlinkert** [comment]
Great! If you want to try building the docs, you can do:

```sh
$ npm cache clean && npm i -g verbose/verb#dev verb-generate-readme && verb
```

If that fails, I can build it

**Comment by spacedawwwg** [comment]
Worked a treat!

**Comment by jonschlinkert** [comment]
you're in business!

**Comment by jonschlinkert** [comment]
once you get verb working, it's addictive lol

**Comment by spacedawwwg** [comment]
I really like it! Just need to figure out how best to comment/document 'var_args' using it (not sure i've documented/commented it correctly yet)

**Pull request merged**
