### PR TITLE
Fix markdown by making properties enumerable

### LINKED ISSUE #222: Markdown and MD not loading with the helpers command.
I can't tell if it is intentional or not, but it gave me a lot of headaches. I had to load the file directly to get this to work, and had to reference the property directly, because the property is not enumerable.

In order for this to work better, and be auto-detected, the enumerable property should be set to true for these properties. Otherwise the experience given by helpers.markdown() is very awkward, since it doesn't give you anything.

### PR DESCRIPTION
**Pull request by alisd23**
fixes #222

### CODE REVIEW

**Comment by Ghosh** [comment]
Please merge this, I spent too long trying to get this to work.

**Comment by moberwasserlechner** [comment]
Thanks @alisd23 from me as well. Only with this property the markdown helper was found. Please merge.

**Comment by jonschlinkert** [comment]
On it, I'll get this merged asap, thanks for the pr @alisd23, and thanks for the ping @moberwasserlechner.

**Comment by moberwasserlechner** [comment]
@jonschlinkert thank you :)

**Comment by AurelioDeRosa** [comment]
I hate adding +1s and the like, but I spent one hour trying to figure it out what I was doing wrong. Please merge this PR asap.

**Pull request merged**
